"use strict";
const { v4: uuidv4 } = require("uuid");

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("blogs", [
      {
        id: "07aeff53-31e5-4276-8307-f855b22b6436",
        title: "Wild Patterns Could be the Thing You Need",
        author_name: "Riko Simonsen",
        status: "visible",
        meta_description: "Beautifully designed web application template built with React and Bootstrap to create modern apps and speed up development",
        keywords: "flatlogic, react templates",
        meta_author: "Flatlogic LLC.",
        meta_og_title: "Flatlogic - React, Vue, Angular and Bootstrap Templates and Admin Dashboard Themes",
        meta_og_url: "https://flatlogic-ecommerce.herokuapp.com/",
        meta_og_image: "https://flatlogic-ecommerce-backend.herokuapp.com/images/blogs/content_image_six.jpg",
        meta_fb_id: "712557339116053",
        meta_og_sitename: "Flatlogic",
        post_twitter: "@flatlogic",
        blog_image_one_annotation: "The patterns could be inspired by nature",
        blog_image_two_annotation: "They could look like flowers",
        blog_image_three_annotation: "",
        blog_image_four_annotation: "",
        blog_image_five_annotation: "",
        point_one_title: "Be uptodate with the latest trend",
        point_one_description: "Every year the trendy patterns change, so stay current with your choice.",
        point_two_title: "Try something new!",
        point_two_description: "You can try it out like nothing else. Try different things, share with friends and discover your new favorite parts.",
        point_three_title: "",
        point_three_description: "",
        point_four_title: "",
        point_four_description: "",
        point_five_title: "",
        point_five_description: "",
        epigraph: "These lively patterns will give your wardrobe the look you always wanted. Can you imagine the way it feels to turn your outfit into a dreamy forest or warm lake?",
        first_paragraph: "Patterns are especially now totally in again. Inspired by the 70s and 80s, the motto is: the more extravagant, the better! Even if it seems unusual at first, it can give a certain self-confidence and ensure that you stand out everywhere. With just a few pieces, you look fashionable and as if you had put a lot of thought into the outfit.",
        second_paragraph: "And with patterns you can go in different directions. On the one hand, there are classic variants, such as stripes, checks or polkadots. Or you can try something fancier, with the absolute trend patterns patchwork or animal patterns like leopard and snake. There is no such thing as too much, and the limits are the imagination.",
        third_paragraph: "Of course, a garment with pattern can be combined with more neutral clothes if you want to try out first. But you can also simply combine different patterns with each other. Either they are then all in the same color family, or you experiment around and dress like a rainbow. The choice is yours. Then, with the different seasons, the colors of these patterns change. In summer they are mainly bright and cheerful, in autumn they become more muted. To go with this, you can read our article on Amber Tones!",
        fourth_paragraph: "",
        fifth_paragraph: "",
        createdAt: new Date("2021-09-09T03:24:00"),
        updatedAt: new Date(),
      },
      {
        id: "c4245ff9-6a53-4b13-8539-0b69b442cfd1",
        title: "Amber Tones - A Sophisticated Take On An Extraordinary Color",
        author_name: "Riko Simonsen",
        status: "visible",
        meta_description: "Beautifully designed web application template built with React and Bootstrap to create modern apps and speed up development",
        keywords: "flatlogic, react templates",
        meta_author: "Flatlogic LLC.",
        meta_og_title: "Flatlogic - React, Vue, Angular and Bootstrap Templates and Admin Dashboard Themes",
        meta_og_url: "https://flatlogic-ecommerce.herokuapp.com/",
        meta_og_image: "https://flatlogic-ecommerce-backend.herokuapp.com/images/blogs/content_image_six.jpg",
        meta_fb_id: "712557339116053",
        meta_og_sitename: "Flatlogic",
        post_twitter: "@flatlogic",
        blog_image_one_annotation: "A nice contrast to the nature around you",
        blog_image_two_annotation: "There are a lot of different amber tones",
        blog_image_three_annotation: "",
        blog_image_four_annotation: "",
        blog_image_five_annotation: "",
        point_one_title: "A color so pleasant",
        point_one_description: "The color is soothing and radiates instant warmth.",
        point_two_title: "Combine it with your favorite pieces",
        point_two_description: "Due to the fact that the color is so cozy, it can really be combined with any piece, just give it a try and be excited about new favorite outfits.",
        point_three_title: "",
        point_three_description: "",
        point_four_title: "",
        point_four_description: "",
        point_five_title: "",
        point_five_description: "",
        epigraph: "Nostalgia and comfort are the words that come to mind. Maximum coziness create an unforgettable outfit. You should try this concept.",
        first_paragraph: "Amber Tones are a perfect blend of muted and colored. Because they radiate a warmth without being too flashy. Usually more associated with fall, the color can go with any season, including spring. For this, the saturation can be higher.",
        second_paragraph: "Even if it doesn't seem like it - amber tones can look very classy. For this, amber can be combined with jewel tones, for example. This is an absolute eye-catcher and you automatically look expensive and put together.",
        third_paragraph: "Otherwise, of course, amber can be combined classically with other warm tones. Use yellow, red and orange clothes to be perceived as the personified sunshine. Radiate and shine and infect people with a good mood.",
        fourth_paragraph: "",
        fifth_paragraph: "",
        createdAt: new Date("2021-06-12T03:24:00"),
        updatedAt: new Date(),
      },
      {
        id: "57fbad3f-528a-43b2-83e8-32ba30708194",
        title: "Distant Shores are Waiting For You And Your Wardrobe!",
        author_name: "Viola Gilbert",
        status: "visible",
        meta_description: "Beautifully designed web application template built with React and Bootstrap to create modern apps and speed up development",
        keywords: "flatlogic, react templates",
        meta_author: "Flatlogic LLC.",
        meta_og_title: "Flatlogic - React, Vue, Angular and Bootstrap Templates and Admin Dashboard Themes",
        meta_og_url: "https://flatlogic-ecommerce.herokuapp.com/",
        meta_og_image: "https://flatlogic-ecommerce-backend.herokuapp.com/images/blogs/content_image_six.jpg",
        meta_fb_id: "712557339116053",
        meta_og_sitename: "Flatlogic",
        post_twitter: "@flatlogic",
        blog_image_one_annotation: "Go on your next adventure",
        blog_image_two_annotation: "Let your clothes reflect your mood",
        blog_image_three_annotation: "",
        blog_image_four_annotation: "",
        blog_image_five_annotation: "",
        point_one_title: "Freedom loving with taste",
        point_one_description: "Discovering the world and experiencing new things are your life's dream? Then dress appropriately with the boho style",
        point_two_title: "Makes every day feel like a vacation",
        point_two_description: "Especially when you combine the look with pieces from all over the world, you can feel like you're at the seaside every day.",
        point_three_title: "",
        point_three_description: "",
        point_four_title: "",
        point_four_description: "",
        point_five_title: "",
        point_five_description: "",
        epigraph: "The getaway lifestyle was reimagined. Prepare yourself for the journey to the distant shores. It will give you a calm and relaxing atmosphere for you to always recharge yourself.",
        first_paragraph: "If you are a hippie at heart, you will love the boho style. Because you can live out your romantic and nature-loving side with it totally well. It draws inspiration from different cultures and traditional dresses.",
        second_paragraph: "Among other things, the material used is important for the trend. The clothes should be of high quality and reflect the closeness to nature - that's why linen or cotton are very popular. The fabrics fall airy and emphasize the joy of life of the wearer.",
        third_paragraph: "Besides the clothes, the right accessories play a big role. Statement earrings or necklaces are colorfully combined. Natural materials such as wood or silver are also used here. Add a hat and a big bag to round off the look.",
        fourth_paragraph: "",
        fifth_paragraph: "",
        createdAt: new Date("2021-05-28T03:24:00"),
        updatedAt: new Date(),
      },
      {
        id: "6fd75915-f1f0-447b-b144-c58c03d4df20",
        title: "Vintage Elements Were Reimagined! Use Retro Pieces and Vibrant Colours",
        author_name: "Viola Gilbert",
        status: "visible",
        meta_description: "Beautifully designed web application template built with React and Bootstrap to create modern apps and speed up development",
        keywords: "flatlogic, react templates",
        meta_author: "Flatlogic LLC.",
        meta_og_title: "Flatlogic - React, Vue, Angular and Bootstrap Templates and Admin Dashboard Themes",
        meta_og_url: "https://flatlogic-ecommerce.herokuapp.com/",
        meta_og_image: "https://flatlogic-ecommerce-backend.herokuapp.com/images/blogs/content_image_six.jpg",
        meta_fb_id: "712557339116053",
        meta_og_sitename: "Flatlogic",
        post_twitter: "@flatlogic",
        blog_image_one_annotation: "",
        blog_image_two_annotation: "Vintage means variety",
        blog_image_three_annotation: "",
        blog_image_four_annotation: "It can be real vintage or something new in retro style",
        blog_image_five_annotation: "",
        point_one_title: "Vintage makes you unique",
        point_one_description: "Because you can go in so many different directions, you can let your creativity run wild and express yourself as you like, with different parts from the best times.",
        point_two_title: "Vintage is in the details",
        point_two_description: "You don't have to turn your mom's closet upside down to follow the trend. Even a scarf or a bag can give the outfit that certain something.",
        point_three_title: "",
        point_three_description: "",
        point_four_title: "",
        point_four_description: "",
        point_five_title: "",
        point_five_description: "",
        epigraph: "Provide plenty of contrast to stand out from the crowd. Each and every one of these vintage pieces should mean something to you. In this case, it will be loved by you.",
        first_paragraph: "To be considered vintage, a garment doesn't just have to be old - it also has to be seen as valuable. It may trigger a nostalgic feeling or it may be intended to give the old piece a new shine. All in all, retro looks tell a story.",
        second_paragraph: "Because vintage can come from any era, the clothes are very broad in cut, color and material. But to look truly retro, you should match accessories, shoes, and bags to your clothing. Then you'll really look like you've stepped out of another period.",
        third_paragraph: "So bright colors and loud motifs can pass for vintage just as well as flowing fabric in muted tones. Pants with flared legs are particularly trendy at the moment. Already popular 50 years ago, they are currently setting the tone among young people. Or you can try an elegant two-piece. There are no limits.",
        fourth_paragraph: "",
        fifth_paragraph: "",
        createdAt: new Date("2021-04-01T03:24:00"),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("blogs", null, {});
  },
};
